import Nonadditivity.DeterministicConsequences
import Nonadditivity.HaarPrescribedBound
import Nonadditivity.OperationalCodingTheorem
import Nonadditivity.OperationalConsequences
import Nonadditivity.PrescribedCostCapacity
import Nonadditivity.PrescribedCostScaling
import Nonadditivity.WeylPowersEntropy

#check Nonadditivity.HaarPrescribedDimension.exists_prescribed_channel_with_lower_bound
#print axioms Nonadditivity.HaarPrescribedDimension.exists_prescribed_channel_with_lower_bound
#check Nonadditivity.Operational.operationalCapacity_eq_regularizedHolevoSupremum
#print axioms Nonadditivity.Operational.operationalCapacity_eq_regularizedHolevoSupremum
#check Nonadditivity.OperationalConsequences.exists_small_chi_large_capacity_gain_and_two_use_ratio
#print axioms Nonadditivity.OperationalConsequences.exists_small_chi_large_capacity_gain_and_two_use_ratio
#check Nonadditivity.WeylPowers.positiveTensorPower_weylExtension_holevoBits
#print axioms Nonadditivity.WeylPowers.positiveTensorPower_weylExtension_holevoBits
#check Nonadditivity.PrescribedCost.growingFamily_chi_input_cost_bounds
#print axioms Nonadditivity.PrescribedCost.growingFamily_chi_input_cost_bounds
#check Nonadditivity.PrescribedCost.growingFamily_two_use_input_cost_lower
#print axioms Nonadditivity.PrescribedCost.growingFamily_two_use_input_cost_lower
#check Nonadditivity.DeterministicConsequences.actual_small_large
#print axioms Nonadditivity.DeterministicConsequences.actual_small_large
